package org.yeastrc.limelight.xml.casanovo.annotation;

import org.yeastrc.limelight.limelight_import.api.xml_dto.FilterDirectionType;
import org.yeastrc.limelight.limelight_import.api.xml_dto.FilterablePsmPeptidePositionAnnotationType;

import java.util.ArrayList;
import java.util.List;


public class PSMPeptidePositionAnnotationTypes {

	public static final String CASANOVO_PEPTIDE_POSITION_SCORE = "Casanovo Peptide Position score";

	public static List<FilterablePsmPeptidePositionAnnotationType> getFilterablePsmPeptidePositionAnnotationTypes() {
		List<FilterablePsmPeptidePositionAnnotationType> types = new ArrayList<FilterablePsmPeptidePositionAnnotationType>();

		{
			FilterablePsmPeptidePositionAnnotationType type = new FilterablePsmPeptidePositionAnnotationType();
			type.setName( CASANOVO_PEPTIDE_POSITION_SCORE );
			type.setDescription( "Score generated by Casanovo for each Peptide Position" );
			type.setFilterDirection( FilterDirectionType.ABOVE );

			types.add( type );
		}

		return types;
	}
	
	//  NO Descriptive PSM Peptide Position annotation types

//	/**
//	 * Get the list of descriptive (non-filterable) PSM Peptide Position annotation types
//	 * @return
//	 */
//	public static List<DescriptivePsmPeptidePositionAnnotationType> getDescriptivePsmPeptidePositionPeptidePositionAnnotationTypes() {
//		List<DescriptivePsmPeptidePositionAnnotationType> types = new ArrayList<>();
//
//
//		return types;
//	}
//	
}
